const ItemActionTypes = {
  ITEMS_SELECTED: "ITEMS_SELECTED",
  PAYMENTS_SELECTED: "PAYMENTS_SELECTED",
  TOGGLE_EXPAND: 'TOGGLE_ITEMS_EXPAND',
  RESET_EXPAND: 'RESET_ITEMS_EXPAND',
};

export default ItemActionTypes;
